# Generated by Django 2.1.7 on 2019-07-25 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('avatar', models.ImageField(blank=True, default='aa', upload_to='media/')),
                ('expert_type', models.CharField(choices=[('chef', 'chef'), ('mixologist', 'mixologist')], max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MyGenericModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theFile', models.FileField(blank=True, default='aa', upload_to='media/files/')),
                ('firebase_id_token', models.CharField(max_length=50)),
            ],
        ),
    ]
