# Generated by Django 2.1.7 on 2019-07-28 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen_brigade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='availability',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expert',
            name='best_dish',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='expert',
            name='fb',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='expert',
            name='instagram',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='expert',
            name='rate',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expert',
            name='station',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expert',
            name='twitter',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='expert',
            name='youtube',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='expert',
            name='expert_type',
            field=models.CharField(max_length=50),
        ),
    ]
